// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package ovsmodel

const TransitSwitchTable = "Transit_Switch"

// TransitSwitch defines an object in Transit_Switch table
type TransitSwitch struct {
	UUID        string            `ovsdb:"_uuid"`
	ExternalIDs map[string]string `ovsdb:"external_ids"`
	Name        string            `ovsdb:"name"`
	OtherConfig map[string]string `ovsdb:"other_config"`
}
