//go:build linux && cgo && !agent

// Code generated by generate-database from the incus project - DO NOT EDIT.

package cluster

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"strings"
)

var oVNQoSObjects = RegisterStmt(`
SELECT device_nic_ovn_qos.id, device_nic_ovn_qos.uuid, device_nic_ovn_qos.action, device_nic_ovn_qos.bandwidth, device_nic_ovn_qos.direction, device_nic_ovn_qos.logical_switch, device_nic_ovn_qos.match, device_nic_ovn_qos.priority
  FROM device_nic_ovn_qos
  ORDER BY device_nic_ovn_qos.id
`)

var oVNQoSObjectsByID = RegisterStmt(`
SELECT device_nic_ovn_qos.id, device_nic_ovn_qos.uuid, device_nic_ovn_qos.action, device_nic_ovn_qos.bandwidth, device_nic_ovn_qos.direction, device_nic_ovn_qos.logical_switch, device_nic_ovn_qos.match, device_nic_ovn_qos.priority
  FROM device_nic_ovn_qos
  WHERE ( device_nic_ovn_qos.id = ? )
  ORDER BY device_nic_ovn_qos.id
`)

var oVNQoSObjectsByUUID = RegisterStmt(`
SELECT device_nic_ovn_qos.id, device_nic_ovn_qos.uuid, device_nic_ovn_qos.action, device_nic_ovn_qos.bandwidth, device_nic_ovn_qos.direction, device_nic_ovn_qos.logical_switch, device_nic_ovn_qos.match, device_nic_ovn_qos.priority
  FROM device_nic_ovn_qos
  WHERE ( device_nic_ovn_qos.uuid = ? )
  ORDER BY device_nic_ovn_qos.id
`)

var oVNQoSObjectsByLogicalSwitch = RegisterStmt(`
SELECT device_nic_ovn_qos.id, device_nic_ovn_qos.uuid, device_nic_ovn_qos.action, device_nic_ovn_qos.bandwidth, device_nic_ovn_qos.direction, device_nic_ovn_qos.logical_switch, device_nic_ovn_qos.match, device_nic_ovn_qos.priority
  FROM device_nic_ovn_qos
  WHERE ( device_nic_ovn_qos.logical_switch = ? )
  ORDER BY device_nic_ovn_qos.id
`)

var oVNQoSID = RegisterStmt(`
SELECT device_nic_ovn_qos.id FROM device_nic_ovn_qos
  WHERE device_nic_ovn_qos.uuid = ?
`)

var oVNQoSCreate = RegisterStmt(`
INSERT INTO device_nic_ovn_qos (uuid, action, bandwidth, direction, logical_switch, match, priority)
  VALUES (?, ?, ?, ?, ?, ?, ?)
`)

var oVNQoSUpdate = RegisterStmt(`
UPDATE device_nic_ovn_qos
  SET uuid = ?, action = ?, bandwidth = ?, direction = ?, logical_switch = ?, match = ?, priority = ?
 WHERE id = ?
`)

var oVNQoSDeleteByUUID = RegisterStmt(`
DELETE FROM device_nic_ovn_qos WHERE uuid = ?
`)

var oVNQoSDeleteByLogicalSwitch = RegisterStmt(`
DELETE FROM device_nic_ovn_qos WHERE logical_switch = ?
`)

// oVNQoSColumns returns a string of column names to be used with a SELECT statement for the entity.
// Use this function when building statements to retrieve database entries matching the OVNQoS entity.
func oVNQoSColumns() string {
	return "device_nic_ovn_qos.id, device_nic_ovn_qos.uuid, device_nic_ovn_qos.action, device_nic_ovn_qos.bandwidth, device_nic_ovn_qos.direction, device_nic_ovn_qos.logical_switch, device_nic_ovn_qos.match, device_nic_ovn_qos.priority"
}

// getOVNQoSs can be used to run handwritten sql.Stmts to return a slice of objects.
func getOVNQoSs(ctx context.Context, stmt *sql.Stmt, args ...any) ([]OVNQoS, error) {
	objects := make([]OVNQoS, 0)

	dest := func(scan func(dest ...any) error) error {
		o := OVNQoS{}
		err := scan(&o.ID, &o.UUID, &o.Action, &o.Bandwidth, &o.Direction, &o.LogicalSwitch, &o.Match, &o.Priority)
		if err != nil {
			return err
		}

		objects = append(objects, o)

		return nil
	}

	err := selectObjects(ctx, stmt, dest, args...)
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"device_nic_ovn_qos\" table: %w", err)
	}

	return objects, nil
}

// getOVNQoSsRaw can be used to run handwritten query strings to return a slice of objects.
func getOVNQoSsRaw(ctx context.Context, db dbtx, sql string, args ...any) ([]OVNQoS, error) {
	objects := make([]OVNQoS, 0)

	dest := func(scan func(dest ...any) error) error {
		o := OVNQoS{}
		err := scan(&o.ID, &o.UUID, &o.Action, &o.Bandwidth, &o.Direction, &o.LogicalSwitch, &o.Match, &o.Priority)
		if err != nil {
			return err
		}

		objects = append(objects, o)

		return nil
	}

	err := scan(ctx, db, sql, dest, args...)
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"device_nic_ovn_qos\" table: %w", err)
	}

	return objects, nil
}

// GetOVNQoSs returns all available OVNQoSs.
// generator: OVNQoS GetMany
func GetOVNQoSs(ctx context.Context, db dbtx, filters ...OVNQoSFilter) (_ []OVNQoS, _err error) {
	defer func() {
		_err = mapErr(_err, "OVNQoS")
	}()

	var err error

	// Result slice.
	objects := make([]OVNQoS, 0)

	// Pick the prepared statement and arguments to use based on active criteria.
	var sqlStmt *sql.Stmt
	args := []any{}
	queryParts := [2]string{}

	if len(filters) == 0 {
		sqlStmt, err = Stmt(db, oVNQoSObjects)
		if err != nil {
			return nil, fmt.Errorf("Failed to get \"oVNQoSObjects\" prepared statement: %w", err)
		}
	}

	for i, filter := range filters {
		if filter.UUID != nil && filter.ID == nil && filter.LogicalSwitch == nil {
			args = append(args, []any{filter.UUID}...)
			if len(filters) == 1 {
				sqlStmt, err = Stmt(db, oVNQoSObjectsByUUID)
				if err != nil {
					return nil, fmt.Errorf("Failed to get \"oVNQoSObjectsByUUID\" prepared statement: %w", err)
				}

				break
			}

			query, err := StmtString(oVNQoSObjectsByUUID)
			if err != nil {
				return nil, fmt.Errorf("Failed to get \"oVNQoSObjects\" prepared statement: %w", err)
			}

			parts := strings.SplitN(query, "ORDER BY", 2)
			if i == 0 {
				copy(queryParts[:], parts)
				continue
			}

			_, where, _ := strings.Cut(parts[0], "WHERE")
			queryParts[0] += "OR" + where
		} else if filter.LogicalSwitch != nil && filter.ID == nil && filter.UUID == nil {
			args = append(args, []any{filter.LogicalSwitch}...)
			if len(filters) == 1 {
				sqlStmt, err = Stmt(db, oVNQoSObjectsByLogicalSwitch)
				if err != nil {
					return nil, fmt.Errorf("Failed to get \"oVNQoSObjectsByLogicalSwitch\" prepared statement: %w", err)
				}

				break
			}

			query, err := StmtString(oVNQoSObjectsByLogicalSwitch)
			if err != nil {
				return nil, fmt.Errorf("Failed to get \"oVNQoSObjects\" prepared statement: %w", err)
			}

			parts := strings.SplitN(query, "ORDER BY", 2)
			if i == 0 {
				copy(queryParts[:], parts)
				continue
			}

			_, where, _ := strings.Cut(parts[0], "WHERE")
			queryParts[0] += "OR" + where
		} else if filter.ID != nil && filter.UUID == nil && filter.LogicalSwitch == nil {
			args = append(args, []any{filter.ID}...)
			if len(filters) == 1 {
				sqlStmt, err = Stmt(db, oVNQoSObjectsByID)
				if err != nil {
					return nil, fmt.Errorf("Failed to get \"oVNQoSObjectsByID\" prepared statement: %w", err)
				}

				break
			}

			query, err := StmtString(oVNQoSObjectsByID)
			if err != nil {
				return nil, fmt.Errorf("Failed to get \"oVNQoSObjects\" prepared statement: %w", err)
			}

			parts := strings.SplitN(query, "ORDER BY", 2)
			if i == 0 {
				copy(queryParts[:], parts)
				continue
			}

			_, where, _ := strings.Cut(parts[0], "WHERE")
			queryParts[0] += "OR" + where
		} else if filter.ID == nil && filter.UUID == nil && filter.LogicalSwitch == nil {
			return nil, fmt.Errorf("Cannot filter on empty OVNQoSFilter")
		} else {
			return nil, errors.New("No statement exists for the given Filter")
		}
	}

	// Select.
	if sqlStmt != nil {
		objects, err = getOVNQoSs(ctx, sqlStmt, args...)
	} else {
		queryStr := strings.Join(queryParts[:], "ORDER BY")
		objects, err = getOVNQoSsRaw(ctx, db, queryStr, args...)
	}

	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"device_nic_ovn_qos\" table: %w", err)
	}

	return objects, nil
}

// GetOVNQoS returns the OVNQoS with the given key.
// generator: OVNQoS GetOne
func GetOVNQoS(ctx context.Context, db dbtx, uuid string) (_ *OVNQoS, _err error) {
	defer func() {
		_err = mapErr(_err, "OVNQoS")
	}()

	filter := OVNQoSFilter{}
	filter.UUID = &uuid

	objects, err := GetOVNQoSs(ctx, db, filter)
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"device_nic_ovn_qos\" table: %w", err)
	}

	switch len(objects) {
	case 0:
		return nil, ErrNotFound
	case 1:
		return &objects[0], nil
	default:
		return nil, fmt.Errorf("More than one \"device_nic_ovn_qos\" entry matches")
	}
}

// OVNQoSExists checks if a OVNQoS with the given key exists.
// generator: OVNQoS Exists
func OVNQoSExists(ctx context.Context, db dbtx, uuid string) (_ bool, _err error) {
	defer func() {
		_err = mapErr(_err, "OVNQoS")
	}()

	stmt, err := Stmt(db, oVNQoSID)
	if err != nil {
		return false, fmt.Errorf("Failed to get \"oVNQoSID\" prepared statement: %w", err)
	}

	row := stmt.QueryRowContext(ctx, uuid)
	var id int64
	err = row.Scan(&id)
	if errors.Is(err, sql.ErrNoRows) {
		return false, nil
	}

	if err != nil {
		return false, fmt.Errorf("Failed to get \"device_nic_ovn_qos\" ID: %w", err)
	}

	return true, nil
}

// CreateOVNQoS adds a new OVNQoS to the database.
// generator: OVNQoS Create
func CreateOVNQoS(ctx context.Context, db dbtx, object OVNQoS) (_ int64, _err error) {
	defer func() {
		_err = mapErr(_err, "OVNQoS")
	}()

	args := make([]any, 7)

	// Populate the statement arguments.
	args[0] = object.UUID
	args[1] = object.Action
	args[2] = object.Bandwidth
	args[3] = object.Direction
	args[4] = object.LogicalSwitch
	args[5] = object.Match
	args[6] = object.Priority

	// Prepared statement to use.
	stmt, err := Stmt(db, oVNQoSCreate)
	if err != nil {
		return -1, fmt.Errorf("Failed to get \"oVNQoSCreate\" prepared statement: %w", err)
	}

	// Execute the statement.
	result, err := stmt.Exec(args...)
	if err != nil && strings.HasPrefix(err.Error(), "UNIQUE constraint failed:") {
		return -1, ErrConflict
	}

	if err != nil {
		return -1, fmt.Errorf("Failed to create \"device_nic_ovn_qos\" entry: %w", err)
	}

	id, err := result.LastInsertId()
	if err != nil {
		return -1, fmt.Errorf("Failed to fetch \"device_nic_ovn_qos\" entry ID: %w", err)
	}

	return id, nil
}

// GetOVNQoSID return the ID of the OVNQoS with the given key.
// generator: OVNQoS ID
func GetOVNQoSID(ctx context.Context, db tx, uuid string) (_ int64, _err error) {
	defer func() {
		_err = mapErr(_err, "OVNQoS")
	}()

	stmt, err := Stmt(db, oVNQoSID)
	if err != nil {
		return -1, fmt.Errorf("Failed to get \"oVNQoSID\" prepared statement: %w", err)
	}

	row := stmt.QueryRowContext(ctx, uuid)
	var id int64
	err = row.Scan(&id)
	if errors.Is(err, sql.ErrNoRows) {
		return -1, ErrNotFound
	}

	if err != nil {
		return -1, fmt.Errorf("Failed to get \"device_nic_ovn_qos\" ID: %w", err)
	}

	return id, nil
}

// UpdateOVNQoS updates the OVNQoS matching the given key parameters.
// generator: OVNQoS Update
func UpdateOVNQoS(ctx context.Context, db tx, uuid string, object OVNQoS) (_err error) {
	defer func() {
		_err = mapErr(_err, "OVNQoS")
	}()

	id, err := GetOVNQoSID(ctx, db, uuid)
	if err != nil {
		return err
	}

	stmt, err := Stmt(db, oVNQoSUpdate)
	if err != nil {
		return fmt.Errorf("Failed to get \"oVNQoSUpdate\" prepared statement: %w", err)
	}

	result, err := stmt.Exec(object.UUID, object.Action, object.Bandwidth, object.Direction, object.LogicalSwitch, object.Match, object.Priority, id)
	if err != nil {
		return fmt.Errorf("Update \"device_nic_ovn_qos\" entry failed: %w", err)
	}

	n, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("Fetch affected rows: %w", err)
	}

	if n != 1 {
		return fmt.Errorf("Query updated %d rows instead of 1", n)
	}

	return nil
}

// DeleteOVNQoS deletes the OVNQoS matching the given key parameters.
// generator: OVNQoS DeleteOne-by-UUID
func DeleteOVNQoS(ctx context.Context, db dbtx, uuid string) (_err error) {
	defer func() {
		_err = mapErr(_err, "OVNQoS")
	}()

	stmt, err := Stmt(db, oVNQoSDeleteByUUID)
	if err != nil {
		return fmt.Errorf("Failed to get \"oVNQoSDeleteByUUID\" prepared statement: %w", err)
	}

	result, err := stmt.Exec(uuid)
	if err != nil {
		return fmt.Errorf("Delete \"device_nic_ovn_qos\": %w", err)
	}

	n, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("Fetch affected rows: %w", err)
	}

	if n == 0 {
		return ErrNotFound
	} else if n > 1 {
		return fmt.Errorf("Query deleted %d OVNQoS rows instead of 1", n)
	}

	return nil
}

// DeleteOVNQoSs deletes the OVNQoS matching the given key parameters.
// generator: OVNQoS DeleteMany-by-LogicalSwitch
func DeleteOVNQoSs(ctx context.Context, db dbtx, logicalSwitch string) (_err error) {
	defer func() {
		_err = mapErr(_err, "OVNQoS")
	}()

	stmt, err := Stmt(db, oVNQoSDeleteByLogicalSwitch)
	if err != nil {
		return fmt.Errorf("Failed to get \"oVNQoSDeleteByLogicalSwitch\" prepared statement: %w", err)
	}

	result, err := stmt.Exec(logicalSwitch)
	if err != nil {
		return fmt.Errorf("Delete \"device_nic_ovn_qos\": %w", err)
	}

	_, err = result.RowsAffected()
	if err != nil {
		return fmt.Errorf("Fetch affected rows: %w", err)
	}

	return nil
}
