//go:build linux && cgo && !agent

// Code generated by generate-database from the incus project - DO NOT EDIT.

package cluster

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"strings"
)

var networkPeerGroupObjects = RegisterStmt(`
SELECT network_peer_groups.id, network_peer_groups.name, network_peer_groups.description
  FROM network_peer_groups
  ORDER BY network_peer_groups.name
`)

var networkPeerGroupObjectsByName = RegisterStmt(`
SELECT network_peer_groups.id, network_peer_groups.name, network_peer_groups.description
  FROM network_peer_groups
  WHERE ( network_peer_groups.name = ? )
  ORDER BY network_peer_groups.name
`)

var networkPeerGroupObjectsByID = RegisterStmt(`
SELECT network_peer_groups.id, network_peer_groups.name, network_peer_groups.description
  FROM network_peer_groups
  WHERE ( network_peer_groups.id = ? )
  ORDER BY network_peer_groups.name
`)

var networkPeerGroupCreate = RegisterStmt(`
INSERT INTO network_peer_groups (name, description)
  VALUES (?, ?)
`)

var networkPeerGroupID = RegisterStmt(`
SELECT network_peer_groups.id FROM network_peer_groups
  WHERE network_peer_groups.name = ?
`)

var networkPeerGroupDeleteByName = RegisterStmt(`
DELETE FROM network_peer_groups WHERE name = ?
`)

// networkPeerGroupColumns returns a string of column names to be used with a SELECT statement for the entity.
// Use this function when building statements to retrieve database entries matching the NetworkPeerGroup entity.
func networkPeerGroupColumns() string {
	return "network_peer_groups.id, network_peer_groups.name, network_peer_groups.description"
}

// getNetworkPeerGroups can be used to run handwritten sql.Stmts to return a slice of objects.
func getNetworkPeerGroups(ctx context.Context, stmt *sql.Stmt, args ...any) ([]NetworkPeerGroup, error) {
	objects := make([]NetworkPeerGroup, 0)

	dest := func(scan func(dest ...any) error) error {
		n := NetworkPeerGroup{}
		err := scan(&n.ID, &n.Name, &n.Description)
		if err != nil {
			return err
		}

		objects = append(objects, n)

		return nil
	}

	err := selectObjects(ctx, stmt, dest, args...)
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"network_peer_groups\" table: %w", err)
	}

	return objects, nil
}

// getNetworkPeerGroupsRaw can be used to run handwritten query strings to return a slice of objects.
func getNetworkPeerGroupsRaw(ctx context.Context, db dbtx, sql string, args ...any) ([]NetworkPeerGroup, error) {
	objects := make([]NetworkPeerGroup, 0)

	dest := func(scan func(dest ...any) error) error {
		n := NetworkPeerGroup{}
		err := scan(&n.ID, &n.Name, &n.Description)
		if err != nil {
			return err
		}

		objects = append(objects, n)

		return nil
	}

	err := scan(ctx, db, sql, dest, args...)
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"network_peer_groups\" table: %w", err)
	}

	return objects, nil
}

// GetNetworkPeerGroups returns all available network_peer_groups.
// generator: network_peer_group GetMany
func GetNetworkPeerGroups(ctx context.Context, db dbtx, filters ...NetworkPeerGroupFilter) (_ []NetworkPeerGroup, _err error) {
	defer func() {
		_err = mapErr(_err, "Network_peer_group")
	}()

	var err error

	// Result slice.
	objects := make([]NetworkPeerGroup, 0)

	// Pick the prepared statement and arguments to use based on active criteria.
	var sqlStmt *sql.Stmt
	args := []any{}
	queryParts := [2]string{}

	if len(filters) == 0 {
		sqlStmt, err = Stmt(db, networkPeerGroupObjects)
		if err != nil {
			return nil, fmt.Errorf("Failed to get \"networkPeerGroupObjects\" prepared statement: %w", err)
		}
	}

	for i, filter := range filters {
		if filter.Name != nil && filter.ID == nil {
			args = append(args, []any{filter.Name}...)
			if len(filters) == 1 {
				sqlStmt, err = Stmt(db, networkPeerGroupObjectsByName)
				if err != nil {
					return nil, fmt.Errorf("Failed to get \"networkPeerGroupObjectsByName\" prepared statement: %w", err)
				}

				break
			}

			query, err := StmtString(networkPeerGroupObjectsByName)
			if err != nil {
				return nil, fmt.Errorf("Failed to get \"networkPeerGroupObjects\" prepared statement: %w", err)
			}

			parts := strings.SplitN(query, "ORDER BY", 2)
			if i == 0 {
				copy(queryParts[:], parts)
				continue
			}

			_, where, _ := strings.Cut(parts[0], "WHERE")
			queryParts[0] += "OR" + where
		} else if filter.ID != nil && filter.Name == nil {
			args = append(args, []any{filter.ID}...)
			if len(filters) == 1 {
				sqlStmt, err = Stmt(db, networkPeerGroupObjectsByID)
				if err != nil {
					return nil, fmt.Errorf("Failed to get \"networkPeerGroupObjectsByID\" prepared statement: %w", err)
				}

				break
			}

			query, err := StmtString(networkPeerGroupObjectsByID)
			if err != nil {
				return nil, fmt.Errorf("Failed to get \"networkPeerGroupObjects\" prepared statement: %w", err)
			}

			parts := strings.SplitN(query, "ORDER BY", 2)
			if i == 0 {
				copy(queryParts[:], parts)
				continue
			}

			_, where, _ := strings.Cut(parts[0], "WHERE")
			queryParts[0] += "OR" + where
		} else if filter.ID == nil && filter.Name == nil {
			return nil, fmt.Errorf("Cannot filter on empty NetworkPeerGroupFilter")
		} else {
			return nil, errors.New("No statement exists for the given Filter")
		}
	}

	// Select.
	if sqlStmt != nil {
		objects, err = getNetworkPeerGroups(ctx, sqlStmt, args...)
	} else {
		queryStr := strings.Join(queryParts[:], "ORDER BY")
		objects, err = getNetworkPeerGroupsRaw(ctx, db, queryStr, args...)
	}

	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"network_peer_groups\" table: %w", err)
	}

	return objects, nil
}

// GetNetworkPeerGroup returns the network_peer_group with the given key.
// generator: network_peer_group GetOne
func GetNetworkPeerGroup(ctx context.Context, db dbtx, name string) (_ *NetworkPeerGroup, _err error) {
	defer func() {
		_err = mapErr(_err, "Network_peer_group")
	}()

	filter := NetworkPeerGroupFilter{}
	filter.Name = &name

	objects, err := GetNetworkPeerGroups(ctx, db, filter)
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"network_peer_groups\" table: %w", err)
	}

	switch len(objects) {
	case 0:
		return nil, ErrNotFound
	case 1:
		return &objects[0], nil
	default:
		return nil, fmt.Errorf("More than one \"network_peer_groups\" entry matches")
	}
}

// NetworkPeerGroupExists checks if a network_peer_group with the given key exists.
// generator: network_peer_group Exists
func NetworkPeerGroupExists(ctx context.Context, db dbtx, name string) (_ bool, _err error) {
	defer func() {
		_err = mapErr(_err, "Network_peer_group")
	}()

	stmt, err := Stmt(db, networkPeerGroupID)
	if err != nil {
		return false, fmt.Errorf("Failed to get \"networkPeerGroupID\" prepared statement: %w", err)
	}

	row := stmt.QueryRowContext(ctx, name)
	var id int64
	err = row.Scan(&id)
	if errors.Is(err, sql.ErrNoRows) {
		return false, nil
	}

	if err != nil {
		return false, fmt.Errorf("Failed to get \"network_peer_groups\" ID: %w", err)
	}

	return true, nil
}

// CreateNetworkPeerGroup adds a new network_peer_group to the database.
// generator: network_peer_group Create
func CreateNetworkPeerGroup(ctx context.Context, db dbtx, object NetworkPeerGroup) (_ int64, _err error) {
	defer func() {
		_err = mapErr(_err, "Network_peer_group")
	}()

	args := make([]any, 2)

	// Populate the statement arguments.
	args[0] = object.Name
	args[1] = object.Description

	// Prepared statement to use.
	stmt, err := Stmt(db, networkPeerGroupCreate)
	if err != nil {
		return -1, fmt.Errorf("Failed to get \"networkPeerGroupCreate\" prepared statement: %w", err)
	}

	// Execute the statement.
	result, err := stmt.Exec(args...)
	if err != nil && strings.HasPrefix(err.Error(), "UNIQUE constraint failed:") {
		return -1, ErrConflict
	}

	if err != nil {
		return -1, fmt.Errorf("Failed to create \"network_peer_groups\" entry: %w", err)
	}

	id, err := result.LastInsertId()
	if err != nil {
		return -1, fmt.Errorf("Failed to fetch \"network_peer_groups\" entry ID: %w", err)
	}

	return id, nil
}

// GetNetworkPeerGroupID return the ID of the network_peer_group with the given key.
// generator: network_peer_group ID
func GetNetworkPeerGroupID(ctx context.Context, db tx, name string) (_ int64, _err error) {
	defer func() {
		_err = mapErr(_err, "Network_peer_group")
	}()

	stmt, err := Stmt(db, networkPeerGroupID)
	if err != nil {
		return -1, fmt.Errorf("Failed to get \"networkPeerGroupID\" prepared statement: %w", err)
	}

	row := stmt.QueryRowContext(ctx, name)
	var id int64
	err = row.Scan(&id)
	if errors.Is(err, sql.ErrNoRows) {
		return -1, ErrNotFound
	}

	if err != nil {
		return -1, fmt.Errorf("Failed to get \"network_peer_groups\" ID: %w", err)
	}

	return id, nil
}

// DeleteNetworkPeerGroup deletes the network_peer_group matching the given key parameters.
// generator: network_peer_group DeleteOne-by-Name
func DeleteNetworkPeerGroup(ctx context.Context, db dbtx, name string) (_err error) {
	defer func() {
		_err = mapErr(_err, "Network_peer_group")
	}()

	stmt, err := Stmt(db, networkPeerGroupDeleteByName)
	if err != nil {
		return fmt.Errorf("Failed to get \"networkPeerGroupDeleteByName\" prepared statement: %w", err)
	}

	result, err := stmt.Exec(name)
	if err != nil {
		return fmt.Errorf("Delete \"network_peer_groups\": %w", err)
	}

	n, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("Fetch affected rows: %w", err)
	}

	if n == 0 {
		return ErrNotFound
	} else if n > 1 {
		return fmt.Errorf("Query deleted %d NetworkPeerGroup rows instead of 1", n)
	}

	return nil
}
