//go:build linux && cgo && !agent

// Code generated by generate-database from the incus project - DO NOT EDIT.

package cluster

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"strings"
)

var instanceSnapshotPropertyObjects = RegisterStmt(`
SELECT instances_snapshots_property.id, instances_snapshots_property.instance_snapshot_id, instances_snapshots_property.ephemeral, instances_snapshots_property.stateful, coalesce(instances_snapshots_property.description, '')
  FROM instances_snapshots_property
  ORDER BY instances_snapshots_property.instance_snapshot_id
`)

var instanceSnapshotPropertyObjectsByID = RegisterStmt(`
SELECT instances_snapshots_property.id, instances_snapshots_property.instance_snapshot_id, instances_snapshots_property.ephemeral, instances_snapshots_property.stateful, coalesce(instances_snapshots_property.description, '')
  FROM instances_snapshots_property
  WHERE ( instances_snapshots_property.id = ? )
  ORDER BY instances_snapshots_property.instance_snapshot_id
`)

var instanceSnapshotPropertyObjectsByInstanceSnapshotID = RegisterStmt(`
SELECT instances_snapshots_property.id, instances_snapshots_property.instance_snapshot_id, instances_snapshots_property.ephemeral, instances_snapshots_property.stateful, coalesce(instances_snapshots_property.description, '')
  FROM instances_snapshots_property
  WHERE ( instances_snapshots_property.instance_snapshot_id = ? )
  ORDER BY instances_snapshots_property.instance_snapshot_id
`)

var instanceSnapshotPropertyCreate = RegisterStmt(`
INSERT INTO instances_snapshots_property (instance_snapshot_id, ephemeral, stateful, description)
  VALUES (?, ?, ?, ?)
`)

var instanceSnapshotPropertyDeleteByInstanceSnapshotID = RegisterStmt(`
DELETE FROM instances_snapshots_property WHERE instance_snapshot_id = ?
`)

// instanceSnapshotPropertyColumns returns a string of column names to be used with a SELECT statement for the entity.
// Use this function when building statements to retrieve database entries matching the InstanceSnapshotProperty entity.
func instanceSnapshotPropertyColumns() string {
	return "instances_snapshots_property.id, instances_snapshots_property.instance_snapshot_id, instances_snapshots_property.ephemeral, instances_snapshots_property.stateful, coalesce(instances_snapshots_property.description, '')"
}

// getInstanceSnapshotProperties can be used to run handwritten sql.Stmts to return a slice of objects.
func getInstanceSnapshotProperties(ctx context.Context, stmt *sql.Stmt, args ...any) ([]InstanceSnapshotProperty, error) {
	objects := make([]InstanceSnapshotProperty, 0)

	dest := func(scan func(dest ...any) error) error {
		i := InstanceSnapshotProperty{}
		err := scan(&i.ID, &i.InstanceSnapshotID, &i.Ephemeral, &i.Stateful, &i.Description)
		if err != nil {
			return err
		}

		objects = append(objects, i)

		return nil
	}

	err := selectObjects(ctx, stmt, dest, args...)
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"instances_snapshots_property\" table: %w", err)
	}

	return objects, nil
}

// getInstanceSnapshotPropertiesRaw can be used to run handwritten query strings to return a slice of objects.
func getInstanceSnapshotPropertiesRaw(ctx context.Context, db dbtx, sql string, args ...any) ([]InstanceSnapshotProperty, error) {
	objects := make([]InstanceSnapshotProperty, 0)

	dest := func(scan func(dest ...any) error) error {
		i := InstanceSnapshotProperty{}
		err := scan(&i.ID, &i.InstanceSnapshotID, &i.Ephemeral, &i.Stateful, &i.Description)
		if err != nil {
			return err
		}

		objects = append(objects, i)

		return nil
	}

	err := scan(ctx, db, sql, dest, args...)
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"instances_snapshots_property\" table: %w", err)
	}

	return objects, nil
}

// GetInstanceSnapshotProperties returns all available instance_snapshot_properties.
// generator: instance_snapshot_property GetMany
func GetInstanceSnapshotProperties(ctx context.Context, db dbtx, filters ...InstanceSnapshotPropertyFilter) (_ []InstanceSnapshotProperty, _err error) {
	defer func() {
		_err = mapErr(_err, "Instance_snapshot_property")
	}()

	var err error

	// Result slice.
	objects := make([]InstanceSnapshotProperty, 0)

	// Pick the prepared statement and arguments to use based on active criteria.
	var sqlStmt *sql.Stmt
	args := []any{}
	queryParts := [2]string{}

	if len(filters) == 0 {
		sqlStmt, err = Stmt(db, instanceSnapshotPropertyObjects)
		if err != nil {
			return nil, fmt.Errorf("Failed to get \"instanceSnapshotPropertyObjects\" prepared statement: %w", err)
		}
	}

	for i, filter := range filters {
		if filter.InstanceSnapshotID != nil && filter.ID == nil {
			args = append(args, []any{filter.InstanceSnapshotID}...)
			if len(filters) == 1 {
				sqlStmt, err = Stmt(db, instanceSnapshotPropertyObjectsByInstanceSnapshotID)
				if err != nil {
					return nil, fmt.Errorf("Failed to get \"instanceSnapshotPropertyObjectsByInstanceSnapshotID\" prepared statement: %w", err)
				}

				break
			}

			query, err := StmtString(instanceSnapshotPropertyObjectsByInstanceSnapshotID)
			if err != nil {
				return nil, fmt.Errorf("Failed to get \"instanceSnapshotPropertyObjects\" prepared statement: %w", err)
			}

			parts := strings.SplitN(query, "ORDER BY", 2)
			if i == 0 {
				copy(queryParts[:], parts)
				continue
			}

			_, where, _ := strings.Cut(parts[0], "WHERE")
			queryParts[0] += "OR" + where
		} else if filter.ID != nil && filter.InstanceSnapshotID == nil {
			args = append(args, []any{filter.ID}...)
			if len(filters) == 1 {
				sqlStmt, err = Stmt(db, instanceSnapshotPropertyObjectsByID)
				if err != nil {
					return nil, fmt.Errorf("Failed to get \"instanceSnapshotPropertyObjectsByID\" prepared statement: %w", err)
				}

				break
			}

			query, err := StmtString(instanceSnapshotPropertyObjectsByID)
			if err != nil {
				return nil, fmt.Errorf("Failed to get \"instanceSnapshotPropertyObjects\" prepared statement: %w", err)
			}

			parts := strings.SplitN(query, "ORDER BY", 2)
			if i == 0 {
				copy(queryParts[:], parts)
				continue
			}

			_, where, _ := strings.Cut(parts[0], "WHERE")
			queryParts[0] += "OR" + where
		} else if filter.ID == nil && filter.InstanceSnapshotID == nil {
			return nil, fmt.Errorf("Cannot filter on empty InstanceSnapshotPropertyFilter")
		} else {
			return nil, errors.New("No statement exists for the given Filter")
		}
	}

	// Select.
	if sqlStmt != nil {
		objects, err = getInstanceSnapshotProperties(ctx, sqlStmt, args...)
	} else {
		queryStr := strings.Join(queryParts[:], "ORDER BY")
		objects, err = getInstanceSnapshotPropertiesRaw(ctx, db, queryStr, args...)
	}

	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"instances_snapshots_property\" table: %w", err)
	}

	return objects, nil
}

// GetInstanceSnapshotProperty returns the instance_snapshot_property with the given key.
// generator: instance_snapshot_property GetOne
func GetInstanceSnapshotProperty(ctx context.Context, db dbtx, instanceSnapshotID int) (_ *InstanceSnapshotProperty, _err error) {
	defer func() {
		_err = mapErr(_err, "Instance_snapshot_property")
	}()

	filter := InstanceSnapshotPropertyFilter{}
	filter.InstanceSnapshotID = &instanceSnapshotID

	objects, err := GetInstanceSnapshotProperties(ctx, db, filter)
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"instances_snapshots_property\" table: %w", err)
	}

	switch len(objects) {
	case 0:
		return nil, ErrNotFound
	case 1:
		return &objects[0], nil
	default:
		return nil, fmt.Errorf("More than one \"instances_snapshots_property\" entry matches")
	}
}

// CreateInstanceSnapshotProperty adds a new instance_snapshot_property to the database.
// generator: instance_snapshot_property Create
func CreateInstanceSnapshotProperty(ctx context.Context, db dbtx, object InstanceSnapshotProperty) (_ int64, _err error) {
	defer func() {
		_err = mapErr(_err, "Instance_snapshot_property")
	}()

	args := make([]any, 4)

	// Populate the statement arguments.
	args[0] = object.InstanceSnapshotID
	args[1] = object.Ephemeral
	args[2] = object.Stateful
	args[3] = object.Description

	// Prepared statement to use.
	stmt, err := Stmt(db, instanceSnapshotPropertyCreate)
	if err != nil {
		return -1, fmt.Errorf("Failed to get \"instanceSnapshotPropertyCreate\" prepared statement: %w", err)
	}

	// Execute the statement.
	result, err := stmt.Exec(args...)
	if err != nil && strings.HasPrefix(err.Error(), "UNIQUE constraint failed:") {
		return -1, ErrConflict
	}

	if err != nil {
		return -1, fmt.Errorf("Failed to create \"instances_snapshots_property\" entry: %w", err)
	}

	id, err := result.LastInsertId()
	if err != nil {
		return -1, fmt.Errorf("Failed to fetch \"instances_snapshots_property\" entry ID: %w", err)
	}

	return id, nil
}

// DeleteInstanceSnapshotProperty deletes the instance_snapshot_property matching the given key parameters.
// generator: instance_snapshot_property DeleteOne-by-InstanceSnapshotID
func DeleteInstanceSnapshotProperty(ctx context.Context, db dbtx, instanceSnapshotID int) (_err error) {
	defer func() {
		_err = mapErr(_err, "Instance_snapshot_property")
	}()

	stmt, err := Stmt(db, instanceSnapshotPropertyDeleteByInstanceSnapshotID)
	if err != nil {
		return fmt.Errorf("Failed to get \"instanceSnapshotPropertyDeleteByInstanceSnapshotID\" prepared statement: %w", err)
	}

	result, err := stmt.Exec(instanceSnapshotID)
	if err != nil {
		return fmt.Errorf("Delete \"instances_snapshots_property\": %w", err)
	}

	n, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("Fetch affected rows: %w", err)
	}

	if n == 0 {
		return ErrNotFound
	} else if n > 1 {
		return fmt.Errorf("Query deleted %d InstanceSnapshotProperty rows instead of 1", n)
	}

	return nil
}
