#!/bin/sh
set -eu
PREFIX="/var/run/incus_agent"

fail() {
    # Check if we already have an agent in place.
    if [ -x "$PREFIX/incus-agent" ]; then
        echo "$1, reusing existing agent"
        exit 0
    fi

    # Cleanup and fail.
    umount "$PREFIX" >/dev/null 2>&1 || true
    rmdir "$PREFIX" >/dev/null 2>&1 || true
    echo "$1, failing"

    exit 1
}

# Try getting an agent drive.
mkdir -p "$PREFIX.mnt"
mount_9p -o ro -cu "/dev/$(dmesg | grep -o 'vio9p.*: tagged as config' | cut -d: -f1 | head -n1)" "$PREFIX.mnt" >/dev/null 2>&1 || fail "Couldn't mount 9p"

# Setup the mount target.
umount "$PREFIX" >/dev/null 2>&1 || true
mkdir -p "$PREFIX"
mount_tmpfs -m 0700 -u root -g wheel -s 50M tmpfs "$PREFIX"

# Copy the data.
cp -Ra "$PREFIX.mnt/"* "$PREFIX"

# Unmount the temporary mount.
umount "$PREFIX.mnt"
rmdir "$PREFIX.mnt"

exit 0
