// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package ovsmodel

const DatapathTable = "Datapath"

// Datapath defines an object in Datapath table
type Datapath struct {
	UUID               string            `ovsdb:"_uuid"`
	Capabilities       map[string]string `ovsdb:"capabilities"`
	CTZoneDefaultLimit *int              `ovsdb:"ct_zone_default_limit" validate:"omitempty,min=0,max=4294967295"`
	CTZones            map[int]string    `ovsdb:"ct_zones" validate:"dive,keys,min=0,max=65535"`
	DatapathVersion    string            `ovsdb:"datapath_version"`
	ExternalIDs        map[string]string `ovsdb:"external_ids"`
}
