package qmp

import (
	"bufio"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	"golang.org/x/sys/unix"

	"github.com/lxc/incus/v6/shared/logger"
	"github.com/lxc/incus/v6/shared/util"
)

const (
	// EventQueueLength is the queue length of events.
	EventQueueLength = 128

	// ZeroKey is the zero key, which represent err channel key.
	ZeroKey = uint32(0)
)

var (
	monitors     = map[string]*Monitor{}
	monitorsLock sync.Mutex
)

// RingbufSize is the size of the agent serial ringbuffer in bytes.
var RingbufSize = 16

// EventAgentStarted is the event sent once the agent has started.
var EventAgentStarted = "AGENT-STARTED"

// EventVMShutdown is the event sent when VM guest shuts down.
var EventVMShutdown = "SHUTDOWN"

// EventVMShutdownReasonDisconnect is used as the reason when the shutdown event is triggered by a QMP disconnect.
var EventVMShutdownReasonDisconnect = "disconnect"

// EventDiskEjected is used to indicate that a disk device was ejected by the guest.
var EventDiskEjected = "DEVICE_TRAY_MOVED"

// Monitor represents a QMP monitor.
type Monitor struct {
	path string

	// Capability OOB supported or not
	oobSupported bool

	// Underlying connection
	c net.Conn

	// Serialize running command against domain
	mu sync.Mutex

	// Events channel
	events <-chan Event

	// Auto increase command id
	id atomic.Uint32

	// ID: <- chan rawResponse map
	replies sync.Map

	agentStarted      bool
	agentStartedMu    sync.Mutex
	disconnected      bool
	chDisconnect      chan struct{}
	eventHandler      func(name string, data map[string]any)
	serialCharDev     string
	onDisconnectEvent bool

	// QMP Log Path
	logPath string
	// QMP Log File
	logFile *os.File
}

// start handles the background goroutines for event handling and monitoring the ringbuffer.
func (m *Monitor) start() error {
	// Ringbuffer monitoring function.
	checkBuffer := func() {
		// Prepare the response.
		var resp struct {
			Return string `json:"return"`
		}

		// Read the ringbuffer.
		args := map[string]any{
			"device": m.serialCharDev,
			"size":   RingbufSize,
			"format": "utf8",
		}

		err := m.Run("ringbuf-read", args, &resp)
		if err != nil {
			return
		}

		// Extract the last entry.
		entries := strings.Split(resp.Return, "\n")
		if len(entries) > 1 {
			status := entries[len(entries)-2]

			m.agentStartedMu.Lock()
			if status == "STARTED" {
				if !m.agentStarted && m.eventHandler != nil {
					go m.eventHandler(EventAgentStarted, nil)
				}

				m.agentStarted = true
			} else if status == "STOPPED" {
				m.agentStarted = false
			}

			m.agentStartedMu.Unlock()
		}
	}

	// Start event monitoring go routine.
	chEvents, err := m.Events(context.Background())
	if err != nil {
		return err
	}

	go func() {
		logger.Debug("QMP monitor started", logger.Ctx{"path": m.path})
		defer logger.Debug("QMP monitor stopped", logger.Ctx{"path": m.path})

		// Initial read from the ringbuffer.
		go checkBuffer()

		for {
			// Wait for an event, disconnection or timeout.
			select {
			case <-m.chDisconnect:
				return
			case e, more := <-chEvents:
				// Handle media ejection.
				if e.Event == EventDiskEjected {
					id, ok := e.Data["id"].(string)
					if ok {
						go func() {
							err = m.Eject(id)
							if err != nil {
								logger.Warnf("Unable to eject media %q: %v", id, err)
							}
						}()
					}
				}

				// Deliver non-empty events to the event handler.
				if m.eventHandler != nil && e.Event != "" {
					if e.Event == EventVMShutdown {
						// Prefer shutdown event generated by QEMU (contains useful info)
						// and prevent duplicate shutdown event when monitor disconnects.
						m.onDisconnectEvent = false
					}

					go m.eventHandler(e.Event, e.Data)
				}

				// Event channel is closed, lets disconnect.
				if !more {
					// If disconnection happened unexpectedly then send shutdown event if
					// enabled so that VM devices can be cleaned up on the host.
					if m.onDisconnectEvent && m.eventHandler != nil {
						go m.eventHandler(EventVMShutdown, map[string]any{"reason": EventVMShutdownReasonDisconnect})
					}

					m.Disconnect()
					return
				}

				if e.Event == "" {
					logger.Warnf("Unexpected empty event received from qmp event channel")
					time.Sleep(time.Second) // Don't spin if we receive a lot of these.
					continue
				}

				// Check if the ringbuffer was updated (non-blocking).
				go checkBuffer()
			case <-time.After(10 * time.Second):
				// Check if the ringbuffer was updated (non-blocking).
				go checkBuffer()

				continue
			}
		}
	}()

	return nil
}

// ping is used to validate if the QMP socket is still active.
func (m *Monitor) ping() error {
	// Check if disconnected
	if m.disconnected {
		return ErrMonitorDisconnect
	}

	// Query the capabilities to validate the monitor.
	err := m.RunCommand(&Command{Execute: "query-version"}, nil)
	if err != nil {
		m.Disconnect()
		return ErrMonitorDisconnect
	}

	return nil
}

// RunJSON executes a JSON-formatted command.
func (m *Monitor) RunJSON(b []byte, resp any, logok bool) error {
	req := &Command{
		logok: logok,
	}

	err := json.Unmarshal(b, req)
	if err != nil {
		logger.Errorf("failed to unmarshal: %v", err)
		return err
	}

	err = m.runJSON(req, resp)
	if err != nil {
		logger.Errorf("failed to run json: %v", err)
		return err
	}

	return nil
}

func (m *Monitor) runJSON(req *Command, rep any) error {
	// Check if disconnected
	if m.disconnected {
		return ErrMonitorDisconnect
	}
	// req := &Command{}

	// err := json.Unmarshal(b, req)
	err := m.RunCommand(req, rep)
	if err != nil {
		// Confirm the daemon didn't die.
		errPing := m.ping()
		if errPing != nil {
			return errPing
		}

		return err
	}

	return nil
}

// Run executes a command.
func (m *Monitor) Run(cmd string, args any, resp any) error {
	// Construct the command.
	req := &Command{
		Execute:   cmd,
		Arguments: args,
	}

	return m.runJSON(req, resp)
}

// Connect creates or retrieves an existing QMP monitor for the path.
func Connect(path string, serialCharDev string, eventHandler func(name string, data map[string]any), logFile string) (*Monitor, error) {
	monitorsLock.Lock()
	defer monitorsLock.Unlock()

	// Look for an existing monitor.
	monitor, ok := monitors[path]
	if ok {
		monitor.eventHandler = eventHandler
		return monitor, nil
	}

	c, err := net.DialTimeout("unix", path, time.Second)
	if err != nil {
		return nil, err
	}

	monitor = &Monitor{
		path: path,
		c:    c,
	}

	chError := make(chan error, 1)
	go func() {
		err = monitor.connect()
		chError <- err
	}()

	select {
	case err := <-chError:
		if err != nil {
			return nil, err
		}

	case <-time.After(5 * time.Second):
		_ = monitor.disconnect()
		return nil, fmt.Errorf("QMP connection timed out")
	}

	monitor.chDisconnect = make(chan struct{}, 1)
	monitor.eventHandler = eventHandler
	monitor.serialCharDev = serialCharDev

	if util.PathExists(filepath.Dir(logFile)) {
		monitor.logPath = logFile
		err = monitor.initQMPLog()
		if err != nil {
			return nil, err
		}
	}

	// Default to generating a shutdown event when the monitor disconnects so that devices can be
	// cleaned up. This will be disabled after a shutdown event is received from QEMU itself to avoid
	// causing multiple events.
	monitor.onDisconnectEvent = true

	// Spawn goroutines.
	err = monitor.start()
	if err != nil {
		return nil, err
	}

	// Register in global map.
	monitors[path] = monitor

	return monitor, nil
}

// AgenStarted indicates whether an agent has been detected.
func (m *Monitor) AgenStarted() bool {
	m.agentStartedMu.Lock()
	defer m.agentStartedMu.Unlock()

	return m.agentStarted
}

// Disconnect forces a disconnection from QEMU.
func (m *Monitor) Disconnect() {
	monitorsLock.Lock()
	defer monitorsLock.Unlock()

	// Stop all go routines and disconnect from socket.
	if !m.disconnected {
		close(m.chDisconnect)
		m.disconnected = true
		_ = m.disconnect()
	}

	// Remove from the map.
	delete(monitors, m.path)
}

// Wait returns a channel that will be closed on disconnection.
func (m *Monitor) Wait() (chan struct{}, error) {
	// Check if disconnected
	if m.disconnected {
		return nil, ErrMonitorDisconnect
	}

	return m.chDisconnect, nil
}

// SetOnDisconnectEvent enables or disables the on disconnect event.
func (m *Monitor) SetOnDisconnectEvent(enable bool) {
	m.onDisconnectEvent = enable
}

// Disconnect closes the QEMU monitor socket connection.
func (m *Monitor) disconnect() error {
	err := m.c.Close()
	if m.logFile != nil {
		_ = m.logFile.Close()
		m.logFile = nil
	}

	return err
}

// Connect sets up a QEMU QMP connection.
func (m *Monitor) connect() error {
	enc := json.NewEncoder(m.c)
	dec := json.NewDecoder(m.c)

	// Check for banner on startup
	ban := struct {
		QMP struct {
			Capabilities []string `json:"capabilities"`
		} `json:"QMP"`
	}{}

	err := dec.Decode(&ban)
	if err != nil {
		return err
	}

	m.oobSupported = slices.Contains(ban.QMP.Capabilities, "oob")

	// Issue capabilities handshake
	cmd := Command{Execute: "qmp_capabilities"}
	err = enc.Encode(cmd)
	if err != nil {
		return err
	}

	// Check for no error on return
	r := &Response{}
	err = dec.Decode(r)
	if err != nil {
		return err
	}

	if r.Error != nil {
		err = fmt.Errorf("%s: %s", r.Error.Class, r.Error.Desc)
		return err
	}

	// Make sure events dispatch non blocking
	events := make(chan Event, EventQueueLength)

	go m.listen(m.c, events, &m.replies)

	m.events = events

	return nil
}

// Events streams QEMU QMP Events.
//
// Events should only be called once per Socket.  If used with a qemu.Domain,
// qemu.Domain.Events should be called to retrieve events instead.
func (m *Monitor) Events(context.Context) (<-chan Event, error) {
	return m.events, nil
}

// listen listens for incoming data from a QEMU monitor socket.
//
// It determines if the data is an asynchronous event or a response to a
// command, and returns the data on the appropriate channel.
func (m *Monitor) listen(r io.Reader, events chan<- Event, replies *sync.Map) {
	defer close(events)
	scanner := bufio.NewScanner(r)
	for scanner.Scan() {
		e := Event{}

		b := scanner.Bytes()
		err := json.Unmarshal(b, &e)
		if err != nil {
			logger.Errorf("failed to unmarshal event: %v", err)
			continue
		}

		if e.Event != "" {
			// Make sure events dispatch non blocking
			logf := m.eventLog(&e)
			select {
			case events <- e:
				if logf != nil {
					_, err = logf("EVENT(dispatched): %s", b)
				}

			default:
				if logf != nil {
					_, err = logf("EVENT(discarded): %s", b)
				}
			}

			if err != nil {
				logger.Errorf("failed to log the event: %v", err)
			}

			continue
		}

		r := rawResponse{}
		err = json.Unmarshal(b, &r)
		if err != nil {
			logger.Errorf("failed to unmarshal raw response: %v", err)
			continue
		}

		key := r.ID
		if key == ZeroKey { // discard
			logger.Debugf("Discard unknown response: %s", b)
			continue
		}

		val, ok := replies.LoadAndDelete(key)
		if !ok { // discard
			logger.Debug("no need reply, discard")
			continue
		}

		reply, ok := val.(chan rawResponse)
		if !ok { // discard
			logger.Errorf("failed to cast chan rawResponse")
			continue
		}

		// copy raw byte slice to avoid the weird QEMU QMP bug
		r.b = make([]byte, len(b))
		copy(r.b, b)

		reply <- r
	}

	err := scanner.Err()
	if err != nil {
		r := rawResponse{
			err: err,
		}

		errReply := make(chan rawResponse, 1)
		replies.Store(ZeroKey, errReply)
		errReply <- r
	}
}

// RunCommand executes the given QAPI command against a domain's QEMU instance.
// For a list of available QAPI commands, see:
//
//	http://git.qemu.org/?p=qemu.git;a=blob;f=qapi-schema.json;hb=HEAD
func (m *Monitor) RunCommand(req *Command, rep any) error {
	// Just call RunWithFile with no file
	return m.RunWithFile(req, nil, rep)
}

// increaseID increase ID and skip zero.
func (m *Monitor) increaseID() uint32 {
	id := m.id.Add(1)
	if id == ZeroKey {
		id = m.id.Add(1)
	}

	return id
}

func (m *Monitor) writeMsg(b []byte, file *os.File) error {
	if file == nil {
		// Just send a normal command through.
		_, err := m.c.Write(b)
		if err != nil {
			return err
		}
	} else {
		unixConn, ok := m.c.(*net.UnixConn)
		if !ok {
			return fmt.Errorf("RunWithFile only works with unix monitor sockets")
		}

		if !m.oobSupported {
			return fmt.Errorf("The QEMU server doesn't support oob (needed for RunWithFile)")
		}

		// Send the command along with the file descriptor.
		oob := unix.UnixRights(int(file.Fd()))
		_, _, err := unixConn.WriteMsgUnix(b, oob, nil)
		if err != nil {
			return err
		}
	}
	return nil
}

func (m *Monitor) initQMPLog() error {
	if m.logFile == nil && m.logPath != "" {
		var logfile *os.File
		logfile, err := os.OpenFile(m.logPath, os.O_APPEND|os.O_WRONLY|os.O_CREATE, 0o600)
		if err != nil {
			return err
		}

		m.logFile = logfile
	}

	return nil
}

func (m *Monitor) queryLog(req *Command) func(string, ...any) (int, error) {
	if m.logFile == nil {
		return nil
	}

	excludedCommands := []string{"ringbuf-read"}
	logok := req.logok
	if !logok {
		logok = !slices.Contains(excludedCommands, req.Execute)
	}

	if logok {
		logf := func(format string, a ...any) (int, error) {
			format = "[%s] " + format
			a = append([]any{time.Now().Format(time.RFC3339)}, a...)
			return fmt.Fprintf(m.logFile, format, a...)
		}

		return logf
	}

	return nil
}

func (m *Monitor) eventLog(e *Event) func(string, ...any) (int, error) {
	if m.logFile != nil &&
		e != nil && e.Event != "" &&
		util.IsTrue(os.Getenv("INCUS_QMP_EVENTS_DEBUG")) {
		return func(format string, a ...any) (int, error) {
			format = "[%s] " + format
			a = append([]any{time.Now().Format(time.RFC3339)}, a...)
			return fmt.Fprintf(m.logFile, format, a...)
		}
	}
	return nil
}

// RunWithFile behaves like RunCommand but allows for passing a file through
// out-of-band data.
func (m *Monitor) RunWithFile(req *Command, file *os.File, rep any) error {
	// Only allow a single command to be run at a time to ensure that responses
	// to a command cannot be mixed with responses from another command
	m.mu.Lock()
	defer m.mu.Unlock()
	id := m.increaseID()
	req.ID = id
	b, err := json.Marshal(req)
	if err != nil {
		return err
	}

	logf := m.queryLog(req)
	if logf != nil {
		_, err = logf("QUERY: %s\n", b)
		if err != nil {
			return err
		}
	}

	repCh := make(chan rawResponse, 1)
	m.replies.Store(id, repCh)
	err = m.writeMsg(b, file)
	if err != nil {
		m.replies.Delete(id)
		return err
	}

	// Wait for a response or error to our command
	r := <-repCh

	if r.err != nil {
		return r.err
	}

	if rep == nil { // Skip response parsing
		return nil
	}

	// Handle weird QEMU QMP bug:
	//
	//  out := r.b
	//  responses := strings.Split(string(out), "\r\n")
	//  out = []byte(responses[len(responses)-1])
	//
	// The weird bug should be caused by raw response bytes slice not copied in scan
	// loop, the bytes slice has been copied, so remove the workaround.

	if logf != nil {
		_, err = logf("REPLY: %s\n\n", r.b)
		if err != nil {
			return err
		}
	}

	err = json.Unmarshal(r.b, rep)
	if err != nil {
		return err
	}

	return nil
}
